### ISSUE TITLE
阿里的依赖升级之后不可用

### ISSUE THREAD

**Issue by guoddt** [ksyzz/gateway-demo#1]
依赖升级之后，打开gateway的swagger-ui.html，会提示😱 Could not render e, see the console.
```
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.2.2.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

<spring-cloud.version>Hoxton.RELEASE</spring-cloud.version>

<dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>2.1.1.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```

**Comment by ksyzz** [comment]
网关是通过NacosDiscoverClient来获取注册到nacos的服务信息的，然而在Hoxton.RELEASE版本的spring-cloud中，org.springframework.cloud.gateway.discovery.DiscoveryClientRouteDefinitionLocator的构造方法：

```
        @Deprecated
	public DiscoveryClientRouteDefinitionLocator(DiscoveryClient discoveryClient,
			DiscoveryLocatorProperties properties) {
		this(discoveryClient.getClass().getSimpleName(), properties);
		serviceInstances = Flux
				.defer(() -> Flux.fromIterable(discoveryClient.getServices()))
				.map(discoveryClient::getInstances)
				.subscribeOn(Schedulers.boundedElastic());
	}

	public DiscoveryClientRouteDefinitionLocator(ReactiveDiscoveryClient discoveryClient,
			DiscoveryLocatorProperties properties) {
		this(discoveryClient.getClass().getSimpleName(), properties);
		serviceInstances = discoveryClient.getServices()
				.flatMap(service -> discoveryClient.getInstances(service).collectList());
	}
```
第一个构造方法已被弃用，但是com.alibaba.cloud的2.1.1RELEASE版本中，NacosDiscoveryClient继承的仍然是DiscoveryClient而不是ReactiveDiscoveryClient ，所以NacosDiscoverClient无法正常传入构造函数，导致网关无法获取nacos上注册的服务。
有两种解决方案：
1，使用低一级版本的springboot和spring-cloud
2，寻找更高版本的spring-cloud-starter-alibaba-nacos-discovery，其NacosDiscoverClient继承的是ReactiveDiscoveryClient 。（不确定是否存在该版本）

**Comment by guoddt** [comment]
确实通过降级解决，依据spring-cloud-alibaba的毕业版本推荐，使用如下匹配版本解决。
Spring Cloud Greenwich.RELEASE
Spring Cloud Alibaba 2.1.1.RELEASE
Spring Boot 2.1.X.RELEASE

等待未来版本支持Hoxton
[spring-cloud-alibaba版本说明](https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E)
